jobs:
  start-environment:
    -parallelism: 1
    docker:
      - image: alpine:3.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: serverless dynamodb start
      - run: serverless wsgi serve
  newman-collection-run:
    -parallelism: 1
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./SimpleTests.json
orbs:
  newman: postman/newman@0.0.2
version: 2.1
workflows:
  version: 2
  workflow:
    jobs:
      - start-environment
      - newman-collection-run
