jobs:
  deploy:
    parallelism: 1
    executor: serverless/default
    steps:
      - checkout
      - run:
          command: |
            curl -o- -L https://slss.io/install | bash
                      echo "export PATH=$HOME/.serverless/bin:$PATH" >> "$BASH_ENV"
                      source "$BASH_ENV"
            serverless dynamodb install
            serverless dynamodb start
            serverless wsgi serve
          name: deploy
  newman-collection-run:
    parallelism: 1
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./SimpleTests.json
orbs:
  newman: postman/newman@0.0.2
  serverless: circleci/serverless-framework@1.0.1
version: 2.1
workflows:
  version: 2
  workflow:
    jobs:
      - deploy
      - newman-collection-run
