jobs:
  test_my_api:
    parallelism: 1
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./SimpleTests.json

workflows:
  test_and_deploy:
    jobs:
      - sam/deploy:
          name: deploy-staging
          stack-name: staging-stack
          template: ./path/to/template.yml
      - test_my_api:
          requires:
            - deploy-staging

orbs:
  newman: postman/newman@0.0.2
  sam: circleci/aws-sam-serverless@2.1.0
  serverless: circleci/serverless-framework@1.0.1
  aws-cli: circleci/aws-cli@1.3.1
version: 2.1

