jobs:
  deploy:
    parallelism: 1
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          app-name: serverless-framework-orb
          org-name: circleci
      - run:
          command: >
            serverless dynamodb start
            serverless wsgi serve
          name: deploy
  newman-collection-run:
    parallelism: 1
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./SimpleTests.json
orbs:
  newman: postman/newman@0.0.2
  aws-cli: circleci/aws-cli@x.y
  serverless: circleci/serverless-framework@x.y
version: 2.1
workflows:
  version: 2
  workflow:
    jobs:
      - deploy
      - newman-collection-run
